<?php

/**
 * @file
 * Integrates the lite track changes plugin for CKEditor with Drupal.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_libraries_info().
 */
function lite_libraries_info() {
  return [
    'lite' => [
      'name' => 'LITE',
      'vendor url' => 'http://www.loopindex.com/portfolio-item/track-changes-plugin/',
      'download url' => 'http://ckeditor.com/addon/lite',
      'version arguments' => [
        'file' => 'plugin.js',
        // /* Source version: 1.2.26 */
        'pattern' => '/Source version: (\d+\.\d+\.\d+)/',
        'lines' => 1,
      ],
      'files' => [
        'js' => [
          'lite-includes.js',
          'lite-interface.js',
          'plugin.js',
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view_alter().
 */
function lite_entity_view_alter(array &$build, Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  // Add a #post_render callback to act on the rendered HTML of the entity.
  $build['#post_render'][] = '_lite_entity_post_render';
}

/**
 * Hides tracking HTML when viewing entities.
 */
function _lite_entity_post_render($markup, $element) {
  $output = $markup;

  // Only look for tracking elements when an associated class is detected.
  if (strpos($markup, 'ice-ins') !== FALSE || strpos($markup, 'ice-del') !== FALSE) {
    $dom = Html::load($markup);
    $xpath = new \DOMXPath($dom);

    // Remove proposed insertions with the "ice-ins" class.
    foreach ($xpath->query("//ins[contains(concat(' ', normalize-space(@class), ' '), ' ice-ins ')]") as $node) {
      /** @var \DOMElement $node */
      $node->parentNode->removeChild($node);
    }

    // Keep proposed deletions with the "ice-del" class but remove markers.
    foreach ($xpath->query("//del[contains(concat(' ', normalize-space(@class), ' '), ' ice-del ')]") as $node) {
      /** @var \DOMElement $node */
      $text = $node->textContent;
      _lite_replace_node_content($node, $text);
    }

    $output = Html::serialize($dom);
  }

  return $output;
}

/**
 * Replace the contents of a DOMNode.
 *
 * @param \DOMNode $node
 *   A DOMNode object.
 * @param string $content
 *   The text or HTML that will replace the contents of $node.
 */
function _lite_replace_node_content(\DOMNode &$node, $content) {
  if (strlen($content)) {
    // Load the content into a new DOMDocument and retrieve the DOM nodes.
    $replacement_nodes = Html::load($content)->getElementsByTagName('body')
      ->item(0)
      ->childNodes;
  }
  else {
    $replacement_nodes = [$node->ownerDocument->createTextNode('')];
  }

  foreach ($replacement_nodes as $replacement_node) {
    // Import the replacement node from the new DOMDocument into the original
    // one, importing also the child nodes of the replacement node.
    $replacement_node = $node->ownerDocument->importNode($replacement_node, TRUE);
    $node->parentNode->insertBefore($replacement_node, $node);
  }
  $node->parentNode->removeChild($node);
}

/**
 * Implements hook_element_info_alter().
 */
function lite_element_info_alter(array &$types) {
  // Our process callback must run immediately after
  // TextFormat::processFormat().
  if (isset($types['text_format']) && isset($types['text_format']['#process'])) {
    $search_value = ['Drupal\filter\Element\TextFormat', 'processFormat'];
    $key = array_search($search_value, $types['text_format']['#process']);

    if ($key !== FALSE) {
      $key++;
      array_splice($types['text_format']['#process'], $key, 0, 'lite_filter_process_format');
    }
    else {
      $types['text_format']['#process'][] = 'lite_filter_process_format';
    }
  }
}

/**
 * Process callback for form elements that have a text format selector attached.
 *
 * This callback runs after filter_process_format() and performs additional
 * modifications to the form element.
 *
 * @see \Drupal\filter\Element\TextFormat::processFormat()
 */
function lite_filter_process_format(&$element, FormStateInterface $form_state, &$complete_form) {
  // Retrieve the form object from $form_state.
  $form_object = $form_state->getFormObject();

  // Check to see if we're working with a content entity form.
  if ($form_object instanceof Drupal\Core\Entity\ContentEntityForm) {
    // Retrieve the entity related to the form.
    $entity = $form_state->getFormObject()->getEntity();

    // If the entity is new (being created) then disable tracking in order to
    // prevent users from becoming confused if their initial content does not
    // show up after saving the entity unless they've pressed the "accept all
    // changes" button.
    if ($entity->isNew()) {
      // Append #pre_render callback to disable tracking prior to rendering.
      $element['#pre_render'][] = 'lite_disable_tracking';
    }
  }

  return $element;
}

/**
 * Pre-render function to disable text tracking on new entity creation.
 *
 * @see lite_filter_process_format()
 */
function lite_disable_tracking($element) {
  // Retrieve the available formats for the current text_format.
  $format_options = $element['format']['format']['#options'];

  // Loop through each of the available formats, adding a JS setting which
  // disabled tracking for each.
  foreach ($format_options as $format => $label) {
    if (isset($element['#attached']['drupalSettings']['editor']['formats'][$format]['editorSettings'])) {
      $element['#attached']['drupalSettings']['editor']['formats'][$format]['editorSettings']['lite']['isTracking'] = FALSE;
    }
  }

  return $element;
}
